### YamlMime:Tutorial
title: Deploy a Microsoft Teams Rooms on Windows
metadata:
  title: Using Network Planner - example scenario
  description: This is a step-by-step guide to help you deploy a Microsoft Teams Rooms on Windows device.
  audience: IT Pro
  level: Intermediate
  displayType: one-column
  author: mstonysmith
  ms.author: tonysmit
  ms.date: 10/23/2024
  ms.reviewer: mattslomka
  ms.service: msteams
  ms.topic: tutorial
  ms.localizationpriority: medium
  ms.collection: 
  - M365-collaboration
  ms.custom: seo-marvel-apr2020
items:
- durationInMinutes: 2
  content: |


- title: 
  durationInMinutes: 2
  content: |


- title: 
  durationInMinutes: 2
  content: |


- title: 
  durationInMinutes: 5
  content: |


- title: 
  durationInMinutes: 3
  content: |


- title: 
  durationInMinutes: 5
  content: | 
 
- title: 
  durationInMinutes: 1
  content: |
